-- ============================================================================
-- POS-SOLCRAFT — Datos iniciales
-- ============================================================================
--
-- INTENCIONALMENTE VACÍO.
--
-- Este archivo antes sembraba sedes, productos demo, categorías y stock
-- específicos de una instancia particular (Taiwy). Al pasar el sistema a
-- modelo de una-instancia-por-cliente, el seed idempotente compartido dejó
-- de tener sentido: cada cliente arranca con datos propios que se
-- aprovisionan a mano al desplegar su instancia.
--
-- Ver el runbook de aprovisionamiento del cliente para el orden exacto de
-- SQL/UI que crea sedes, warehouses, lista de precios por defecto,
-- "Consumidor final", categorías base y el usuario admin inicial.
--
-- Mantener este archivo como stub evita que el `scripts/` runner falle si
-- algún proceso lo referencia por posición.
-- ============================================================================
